In [12]:
import pandas as pd

excel_file_gdp = "/content/Raw GDP By States.xlsx"
df_gdp = pd.read_excel(excel_file_gdp)
# Delete rows from Unit to Collection Month (index 0-4)
df_gdp = df_gdp.drop(df_gdp.index[0:9]).copy()
display(df_gdp.head())

,Unnamed: 0,New South Wales ; Gross state product: Chain volume measures ;,Victoria ; Gross state product: Chain volume measures ;,Queensland ; Gross state product: Chain volume measures ;,South Australia ; Gross state product: Chain volume measures ;,Western Australia ; Gross state product: Chain volume measures ;,Tasmania ; Gross state product: Chain volume measures ;,Northern Territory ; Gross state product: Chain volume measures ;,Australian Capital Territory ; Gross state product: Chain volume measures ;,Australia ; Gross domestic product: Chain volume measures ;,New South Wales ; Gross state product per capita: Chain volume measures ;,Victoria ; Gross state product per capita: Chain volume measures ;,Queensland ; Gross state product per capita: Chain volume measures ;,South Australia ; Gross state product per capita: Chain volume measures ;,Western Australia ; Gross state product per capita: Chain volume measures ;,Tasmania ; Gross state product per capita: Chain volume measures ;,Northern Territory ; Gross state product per capita: Chain volume measures ;,Australian Capital Territory ; Gross state product per capita: Chain volume measures ;,Australia ; GDP per capita: Chain volume measures ;
9,1990-06-01 00:00:00,355417,228653,152974,66090,121208,18254,12414,16139,984408,61246,52585,53412,46364,75934,39820,76581,57800,58123
10,1991-06-01 00:00:00,356997,222780,153137,65854,121935,18245,12753,16541,980645,60895,50624,52288,45767,75065,39276,77267,58035,57115
11,1992-06-01 00:00:00,357655,219638,158414,64713,125920,18730,12372,16613,984845,60332,49523,52973,44603,76435,39975,74063,56986,56669
12,1993-06-01 00:00:00,367696,230603,168346,66454,131741,19319,12399,17252,1024699,61510,51725,55067,45602,78957,40994,72755,58181,58364
13,1994-06-01 00:00:00,381287,238404,176747,68280,140727,19712,12202,17999,1065486,63335,53373,56451,46732,83253,41677,70292,59898,60141

In [13]:
excel_file_unem = "/content/Raw Unem by States.xlsx"
df_unem = pd.read_excel(excel_file_unem)
# Delete rows from Unit to Collection Month (index 0-4)
df_unem = df_unem.drop(df_unem.index[0:9]).copy()
display(df_unem.head())

,Unnamed: 0,Employment to population ratio ; Persons ; Australia ;,Employment to population ratio ; Persons ; Australia ;.1,Employment to population ratio ; Persons ; Australia ;.2,Employment to population ratio ; Persons ; > New South Wales ;,Employment to population ratio ; Persons ; > New South Wales ;.1,Employment to population ratio ; Persons ; > New South Wales ;.2,Employment to population ratio ; Persons ; > Victoria ;,Employment to population ratio ; Persons ; > Victoria ;.1,Employment to population ratio ; Persons ; > Victoria ;.2,...,Employment to population ratio ; Persons ; > Western Australia ;,Employment to population ratio ; Persons ; > Western Australia ;.1,Employment to population ratio ; Persons ; > Western Australia ;.2,Employment to population ratio ; Persons ; > Tasmania ;,Employment to population ratio ; Persons ; > Tasmania ;.1,Employment to population ratio ; Persons ; > Tasmania ;.2,Employment to population ratio ; Persons ; > Northern Territory ;,Employment to population ratio ; Persons ; > Northern Territory ;.1,Employment to population ratio ; Persons ; > Australian Capital Territory ;,Employment to population ratio ; Persons ; > Australian Capital Territory ;.1
9,1978-02-01 00:00:00,57.269057,57.180099,57.064271,56.424582,56.585257,56.589341,57.83934,57.603394,57.530166,...,59.89631,59.275229,59.139245,54.880473,55.494986,55.344956,63.648604,59.972162,65.322459,65.859342
10,1978-03-01 00:00:00,57.262288,57.127599,57.481846,56.385417,55.991,56.40116,57.955917,57.832485,58.283069,...,59.750641,59.707153,59.854414,54.828031,54.819077,55.525716,63.754715,66.079899,65.605481,65.816452
11,1978-04-01 00:00:00,57.250671,57.333882,57.556859,56.345853,56.282933,56.483808,58.042592,58.484204,58.674928,...,59.585495,59.496975,59.875525,54.781274,54.8097,55.457201,63.918515,62.708067,65.827444,64.852359
12,1978-05-01 00:00:00,57.232746,57.294423,57.339793,56.31877,56.33199,56.327212,58.098294,58.273316,58.35065,...,59.415346,59.451845,59.864368,54.749723,54.83993,54.971661,64.098526,65.324005,66.045541,66.763998
13,1978-06-01 00:00:00,57.200119,57.229228,57.205049,56.304686,56.292847,56.313853,58.09701,58.227297,58.198782,...,59.227182,59.537789,59.708176,54.748332,54.382657,54.242717,64.361891,61.521229,66.238228,65.930254

In [14]:
excel_file_cpi = "/content/Raw CPI by States.xlsx"
df_cpi = pd.read_excel(excel_file_cpi)
# Delete rows from Unit to Collection Month (index 0-4)
df_cpi = df_cpi.drop(df_cpi.index[0:9]).copy()
display(df_cpi.head())

,Unnamed: 0,Index Numbers ; All groups CPI ; Sydney ;,Index Numbers ; All groups CPI ; Melbourne ;,Index Numbers ; All groups CPI ; Brisbane ;,Index Numbers ; All groups CPI ; Adelaide ;,Index Numbers ; All groups CPI ; Perth ;,Index Numbers ; All groups CPI ; Hobart ;,Index Numbers ; All groups CPI ; Darwin ;,Index Numbers ; All groups CPI ; Canberra ;,Index Numbers ; All groups CPI ; Australia ;
9,1948-09-01 00:00:00,3.7,3.8,3.7,3.8,3.7,3.8,NaN,3.9,3.7
10,1948-12-01 00:00:00,3.7,3.8,3.7,3.9,3.8,3.9,NaN,4.1,3.8
11,1949-03-01 00:00:00,3.9,3.9,3.8,4,3.9,4,NaN,4.1,3.9
12,1949-06-01 00:00:00,3.9,4,3.9,4,4,4.1,NaN,4.2,4
13,1949-09-01 00:00:00,4,4.1,4,4.1,4.1,4.1,NaN,4.3,4.1

In [16]:
# Transpose the DataFrame, using the first row as new headers
df_cpi_transposed = df_cpi.transpose().reset_index()

# Rename columns using the values from the first row
df_cpi_transposed.columns = df_cpi_transposed.iloc[0]
df_cpi_transposed = df_cpi_transposed.drop(0)

# Rename the first column to 'Indicator name'
df_cpi_transposed = df_cpi_transposed.rename(columns={'Unnamed: 0': 'Indicator name'})

# Extract City name from 'Indicator name'
df_cpi_transposed['City Name'] = df_cpi_transposed['Indicator name'].apply(lambda x: x.split(';')[-2].strip() if isinstance(x, str) and len(x.split(';')) > 2 else 'Australia' if isinstance(x, str) and 'Australia' in x else None)

# Melt the DataFrame to long format
df_cpi_normalized = df_cpi_transposed.melt(id_vars=['Indicator name', 'City Name'], var_name='Date', value_name='Value')

# Add a 'State name' column with None values
df_cpi_normalized['State name'] = None

# Keep only relevant columns and reorder
df_cpi_normalized = df_cpi_normalized[['Indicator name', 'State name', 'City Name', 'Date', 'Value']]

display(df_cpi_normalized.head())

,Indicator name,State name,City Name,Date,Value
0,Index Numbers ; All groups CPI ; Sydney ;,None,Sydney,1948-09-01 00:00:00,3.7
1,Index Numbers ; All groups CPI ; Melbourne ;,None,Melbourne,1948-09-01 00:00:00,3.8
2,Index Numbers ; All groups CPI ; Brisbane ;,None,Brisbane,1948-09-01 00:00:00,3.7
3,Index Numbers ; All groups CPI ; Adelaide ;,None,Adelaide,1948-09-01 00:00:00,3.8
4,Index Numbers ; All groups CPI ; Perth ;,None,Perth,1948-09-01 00:00:00,3.7

In [18]:
# Transpose the DataFrame, using the first row as new headers
df_unem_transposed = df_unem.transpose().reset_index()

# Rename columns using the values from the first row
df_unem_transposed.columns = df_unem_transposed.iloc[0]
df_unem_transposed = df_unem_transposed.drop(0)

# Rename the first column to 'Indicator name'
df_unem_transposed = df_unem_transposed.rename(columns={'Unnamed: 0': 'Indicator name'})

# Extract State name from 'Indicator name'
df_unem_transposed['State name'] = df_unem_transposed['Indicator name'].apply(lambda x: x.split('>')[-1].split(';')[0].strip() if isinstance(x, str) and '>' in x else 'Australia' if isinstance(x, str) and 'Australia' in x else None)

# Melt the DataFrame to long format
df_unem_normalized = df_unem_transposed.melt(id_vars=['Indicator name', 'State name'], var_name='Date', value_name='Value')

# Add a 'City Name' column with None values
df_unem_normalized['City Name'] = None

# Keep only relevant columns and reorder
df_unem_normalized = df_unem_normalized[['Indicator name', 'State name', 'City Name', 'Date', 'Value']]

display(df_unem_normalized.head())

,Indicator name,State name,City Name,Date,Value
0,Employment to population ratio ; Persons ; A...,Australia,None,1978-02-01 00:00:00,57.269057
1,Employment to population ratio ; Persons ; A...,Australia,None,1978-02-01 00:00:00,57.180099
2,Employment to population ratio ; Persons ; A...,Australia,None,1978-02-01 00:00:00,57.064271
3,Employment to population ratio ; Persons ; >...,New South Wales,None,1978-02-01 00:00:00,56.424582
4,Employment to population ratio ; Persons ; >...,New South Wales,None,1978-02-01 00:00:00,56.585257

In [20]:
# Transpose the DataFrame, using the first row as new headers
df_gdp_transposed = df_gdp.transpose().reset_index()

# Rename columns using the values from the first row
df_gdp_transposed.columns = df_gdp_transposed.iloc[0]
df_gdp_transposed = df_gdp_transposed.drop(0)

# Rename the first column to 'Indicator name'
df_gdp_transposed = df_gdp_transposed.rename(columns={'Unnamed: 0': 'Indicator name'})

# Extract State name from 'Indicator name'
df_gdp_transposed['State name'] = df_gdp_transposed['Indicator name'].apply(lambda x: x.split(';')[0].strip() if ';' in str(x) else None)

# Melt the DataFrame to long format
df_gdp_normalized = df_gdp_transposed.melt(id_vars=['Indicator name', 'State name'], var_name='Date', value_name='Value')

# Add a 'City Name' column with None values
df_gdp_normalized['City Name'] = None

# Keep only relevant columns and reorder
df_gdp_normalized = df_gdp_normalized[['Indicator name', 'State name', 'City Name', 'Date', 'Value']]

display(df_gdp_normalized.head())

,Indicator name,State name,City Name,Date,Value
0,New South Wales ; Gross state product: Chain ...,New South Wales,None,1990-06-01 00:00:00,355417
1,Victoria ; Gross state product: Chain volume ...,Victoria,None,1990-06-01 00:00:00,228653
2,Queensland ; Gross state product: Chain volum...,Queensland,None,1990-06-01 00:00:00,152974
3,South Australia ; Gross state product: Chain ...,South Australia,None,1990-06-01 00:00:00,66090
4,Western Australia ; Gross state product: Chai...,Western Australia,None,1990-06-01 00:00:00,121208

In [22]:
# Combine the normalized dataframes
combined_df = pd.concat([df_cpi_normalized, df_unem_normalized, df_gdp_normalized], ignore_index=True)

display(combined_df.head())

,Indicator name,State name,City Name,Date,Value
0,Index Numbers ; All groups CPI ; Sydney ;,None,Sydney,1948-09-01 00:00:00,3.7
1,Index Numbers ; All groups CPI ; Melbourne ;,None,Melbourne,1948-09-01 00:00:00,3.8
2,Index Numbers ; All groups CPI ; Brisbane ;,None,Brisbane,1948-09-01 00:00:00,3.7
3,Index Numbers ; All groups CPI ; Adelaide ;,None,Adelaide,1948-09-01 00:00:00,3.8
4,Index Numbers ; All groups CPI ; Perth ;,None,Perth,1948-09-01 00:00:00,3.7

In [24]:
# Export the combined DataFrame to a CSV file
combined_df.to_csv('combined_data.csv', index=False)

print("combined_df exported to combined_data.csv")

combined_df exported to combined_data.csv